y+=300;
if(room!=Rm_ColeteDescarte_3){
	draw_self();
	draw_sprite(Spr_ProximaFase,-1,x,y)
}
else{
	instance_create_layer(x,y,"Instances",obj_retorno);
	draw_sprite(spr_Botao,-1,x,y);
	draw_sprite(spr_retorno,-1,x,y);
}